/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProspeccaoRouteImport } from './routes/_authenticated/prospeccao'
import { Route as AuthenticatedModoLigacaoRouteImport } from './routes/_authenticated/modo-ligacao'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDispositivosRouteImport } from './routes/_authenticated/dispositivos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedClientesClientIdRouteImport } from './routes/_authenticated/clientes/$clientId'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProspeccaoRoute = AuthenticatedProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModoLigacaoRoute =
  AuthenticatedModoLigacaoRouteImport.update({
    id: '/modo-ligacao',
    path: '/modo-ligacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispositivosRoute =
  AuthenticatedDispositivosRouteImport.update({
    id: '/dispositivos',
    path: '/dispositivos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesClientIdRoute =
  AuthenticatedClientesClientIdRouteImport.update({
    id: '/clientes/$clientId',
    path: '/clientes/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/modo-ligacao': typeof AuthenticatedModoLigacaoRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dispositivos': typeof AuthenticatedDispositivosRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/modo-ligacao': typeof AuthenticatedModoLigacaoRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dispositivos': typeof AuthenticatedDispositivosRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/modo-ligacao': typeof AuthenticatedModoLigacaoRoute
  '/_authenticated/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/_authenticated/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/calendario'
    | '/configuracoes'
    | '/dashboard'
    | '/dispositivos'
    | '/insights'
    | '/modo-ligacao'
    | '/prospeccao'
    | '/clientes/$clientId'
    | '/clientes/'
    | '/api/public/hooks/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/agenda'
    | '/calendario'
    | '/configuracoes'
    | '/dashboard'
    | '/dispositivos'
    | '/insights'
    | '/modo-ligacao'
    | '/prospeccao'
    | '/clientes/$clientId'
    | '/clientes'
    | '/api/public/hooks/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/agenda'
    | '/_authenticated/calendario'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/dispositivos'
    | '/_authenticated/insights'
    | '/_authenticated/modo-ligacao'
    | '/_authenticated/prospeccao'
    | '/_authenticated/clientes/$clientId'
    | '/_authenticated/clientes/'
    | '/api/public/hooks/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prospeccao': {
      id: '/_authenticated/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof AuthenticatedProspeccaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modo-ligacao': {
      id: '/_authenticated/modo-ligacao'
      path: '/modo-ligacao'
      fullPath: '/modo-ligacao'
      preLoaderRoute: typeof AuthenticatedModoLigacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispositivos': {
      id: '/_authenticated/dispositivos'
      path: '/dispositivos'
      fullPath: '/dispositivos'
      preLoaderRoute: typeof AuthenticatedDispositivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$clientId': {
      id: '/_authenticated/clientes/$clientId'
      path: '/clientes/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof AuthenticatedClientesClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDispositivosRoute: typeof AuthenticatedDispositivosRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedModoLigacaoRoute: typeof AuthenticatedModoLigacaoRoute
  AuthenticatedProspeccaoRoute: typeof AuthenticatedProspeccaoRoute
  AuthenticatedClientesClientIdRoute: typeof AuthenticatedClientesClientIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDispositivosRoute: AuthenticatedDispositivosRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedModoLigacaoRoute: AuthenticatedModoLigacaoRoute,
  AuthenticatedProspeccaoRoute: AuthenticatedProspeccaoRoute,
  AuthenticatedClientesClientIdRoute: AuthenticatedClientesClientIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
